package qbrick;

public enum CommandType {
    FILE_MESSAGE,
    FILE_REQUEST,
    LIST_REQUEST,
    LIST_RESPONSE,
    PATH_REQUEST,
    PATH_RESPONSE,
    PATH_IN_REQUEST,
    PATH_UP_REQUEST,
    CONSOLE_MESSAGE,
    DELETE_REQUEST,
    DOWNLOAD_STATUS
}